name: botty
dependencies:
  - python=3.8
  - pywin32
  - pip
  - pip:
    - nuitka
    - matplotlib
    - opencv-python
    - transitions
    - mss
    - numpy
    - mouse
    - keyboard
    - graphviz
    - beautifultable
    - zstandard
    - pytweening
    - requests
    - pytest
    - pytest-env
