name: botty
dependencies:
  - python=3.9
  - pywin32
  - pip
  - pip:
    - nuitka
    - pyinstaller
    - opencv-python
    - transitions
    - mss
    - numpy
    - mouse
    - keyboard
    - beautifultable
    - pytweening
    - requests
    - coverage
    - pytest
    - pytest-env
    - pytest-pythonpath
    - graphviz
    - psutil
    - pillow
    - discord.py
